### ISSUE TITLE
Why aren't you uploading?

### ISSUE THREAD

**Issue by ghost** [seanmitch/slowloris#1]
Hello!
I stumbled across this project and i liked it very much!
Could you update it?

**Comment by seanmmitchell** [comment]
A lot of stuff going on in the past few years, coding hasn't been something I have been doing a whole lot of as of late. What updates would you like to see beyond the ones listed, maybe I will do one last push...

**Comment by seanmmitchell** [comment]
Just going to close this, this project is closed.
